[listen]
port = 10_009

[dns]
temp_file_name = "temp_data.pkl"
file_name = "hosts"
redis_cache = false
cache_time = 3

  [[dns.nameserver]]
  ip = "1.2.4.8"
  describe = "cnnic(1.2.4.8)"

  [[dns.nameserver]]
  ip = "114.114.114.114"
  describe = "114.114.114.114"

  [[dns.nameserver]]
  ip = "119.29.29.29"
  describe = "DNSPod(119.29.29.29)"

  [[dns.nameserver]]
  ip = "223.5.5.5"
  describe = "aliyun(223.5.5.5)"

  [[dns.nameserver]]
  ip = "223.6.6.6"
  describe = "aliyun(223.6.6.6)"

  [[dns.nameserver]]
  ip = "1.1.1.1"
  describe = "Cloudflare(1.1.1.1)"

  [[dns.nameserver]]
  ip = "8.8.8.8"
  describe = "Google(8.8.8.8)"

  [[dns.nameserver]]
  ip = "8.8.4.4"
  describe = "Google(8.8.4.4)"

  [[dns.nameserver]]
  ip = "218.201.96.130"
  describe = "mobile_qd(218.201.96.130)"

  [[dns.nameserver]]
  ip = "192.168.254.245"
  describe = "sdu_qd(192.168.254.245)"

  [[dns.nameserver]]
  ip = "192.168.254.141"
  describe = "sdu_jn(192.168.254.141)"

  [[dns.nameserver]]
  ip = "10.102.32.56"
  describe = "smartdns(10.102.32.56)"
