[listen]
port = 10009

[dns]
redis_cache = false # 使用 redis
cache_time = 0 # 单位 s
nameserver = [
    { ip = "1.2.4.8", describe = "cnnic(1.2.4.8)" },
    { ip = "114.114.114.114", describe = "114.114.114.114" },
    { ip = "119.29.29.29", describe = "DNSPod(119.29.29.29)" },
    { ip = "223.5.5.5", describe = "aliyun(223.5.5.5)" },
    { ip = "223.6.6.6", describe = "aliyun(223.6.6.6)" },
    { ip = "1.1.1.1", describe = "Cloudflare(1.1.1.1)" },
    { ip = "8.8.8.8", describe = "Google(8.8.8.8)" },
    { ip = "8.8.4.4", describe = "Google(8.8.4.4)" },
    { ip = "218.201.96.130", describe = "mobile_qd(218.201.96.130)" },
    { ip = "192.168.254.245", describe = "sdu_qd(192.168.254.245)" },
    { ip = "192.168.254.141", describe = "sdu_jn(192.168.254.141)" },
]