name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: cd android && chmod +x gradlew && ./gradlew assemblePureDebug
      - name: Build release
        run: cd android && chmod +x gradlew && ./gradlew assemblePureRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/pure/debug/app-debug.apk
      - name: Upload Artifact release
          uses: actions/upload-artifact@v2
          with:
            name: app-release.apk
            path: android/app/build/outputs/apk/pure/release/app-release.apk
        
