name: Android CI

on: release 
   

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew assemblePureDebug
      - name: Build release
        run: chmod +x gradlew && ./gradlew assemblePureRelease
      - name: Upload Debug
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/pure/debug/app-debug.apk
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/pure/release/app-release.apk
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: android/app/build/outputs/apk/pure/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.YZH_TOKEN }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YZH_TOKEN }}
          file: android/app/build/outputs/apk/pure/debug/app-debug.apk
          asset_name: debug.apk
          tag: ${{ github.ref }}
