name: Android CI

on:
  release:
    types: [ published ]


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew assemblePureDebug
      - name: Build release
        run: chmod +x gradlew && ./gradlew assemblePureRelease
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YZH_TOKEN }}
          file: android/app/build/outputs/apk/pure/release/app-release.apk
          asset_name: release.apk
          tag: ${{ github.ref }}
      - name: Upload debug binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YZH_TOKEN }}
          file: android/app/build/outputs/apk/pure/debug/app-debug.apk
          asset_name: debug.apk
          tag: ${{ github.ref }}
