# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ElectronBuild
on: 
   release:
   push:
       types: [published] 

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - run: npm run buildall
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.YZH_TOKEN }}
        file: ui/build/*.exe
        asset_name: ui.exe
        tag: ${{ github.ref }}
